version: '3.1'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
     image: registry.cn-hangzhou.aliyuncs.com/sl/niuxs:php7.1-fpm-1.0
     volumes:
        - ./:/var/www/html
     links:
       - redis
       - db1
  redis:
    image: redis:latest
    volumes:
      - /Users/sl/docker/data/redis:/data
  db1:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - /Users/sl/docker/data/mysql:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_USER : 123
       MYSQL_PASSWORD : 123
       MYSQL_DATABASE: 123
